spring.application.name=carelog

spring.datasource.url=jdbc:postgresql://${PSQL_URL}:5432/${PSQL_DB}
spring.datasource.username=${PSQL_USER}
spring.datasource.password=${PSQL_PW}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect