spring.application.name=carelog

# DataSource
spring.datasource.url=jdbc:postgresql://${PSQL_URL}:5432/${PSQL_DB}
spring.datasource.username=${PSQL_USER}
spring.datasource.password=${PSQL_PW}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Jasypt
jasypt.encryptor.password=${JASYPT_PASSWORD}