spring.application.name=carelog
# Servlet Context Path
#spring.mvc.servlet.path=/api/v1
server.servlet.context-path=/api/v1
# DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100
# ?????? ?? ?? ??
logging.level.carelog.carelog=DEBUG
# LoggingAspect? ?? ??
logging.level.carelog.carelog.common.config.LoggingAspect=INFO
# Jasypt
jasypt.encryptor.password=${JASYPT_PASSWORD}
# Springdoc (Swagger UI)
springdoc.version=v1.0.0
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.springframework.security=DEBUG