-- Carelog 기존 스키마 baseline.
-- ddl-auto:update로 운영 중이던 스키마를 Hibernate가 생성한 실제 DDL 그대로 재현한다
-- (임시 Postgres 16 컨테이너에 ddl-auto=create로 기동 후 pg_dump --schema-only로 추출, 손으로 추정하지 않음).
-- 기존 비어있지 않은 DB는 Flyway baseline-on-migrate로 이 버전을 기준선으로 삼고,
-- 신규 빈 DB는 이 스크립트부터 실행해 동일한 스키마를 만든다.

CREATE TABLE journal_templates (
    created_at timestamp(6) with time zone NOT NULL,
    journal_templates_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    organization_id uuid NOT NULL,
    public_id uuid NOT NULL,
    created_by character varying(255),
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_by character varying(255),
    fields jsonb NOT NULL,
    CONSTRAINT journal_templates_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

ALTER TABLE journal_templates ALTER COLUMN journal_templates_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME journal_templates_journal_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE refresh_token (
    created_at timestamp(6) with time zone NOT NULL,
    refresh_token_id bigint NOT NULL,
    token_expires_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    refresh_token character varying(500) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    user_id character varying(255) NOT NULL
);

ALTER TABLE refresh_token ALTER COLUMN refresh_token_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refresh_token_refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE relation_journals (
    visit_date date NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    previous_id bigint,
    relation_id bigint NOT NULL,
    relation_journals_id bigint NOT NULL,
    template_id bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    organization_id uuid NOT NULL,
    public_id uuid NOT NULL,
    created_by character varying(255),
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_by character varying(255),
    case_data jsonb NOT NULL,
    private_data jsonb,
    CONSTRAINT relation_journals_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUPERSEDED'::character varying])::text[])))
);

ALTER TABLE relation_journals ALTER COLUMN relation_journals_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME relation_journals_relation_journals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE relations (
    created_at timestamp(6) with time zone NOT NULL,
    customer_id bigint NOT NULL,
    deleted_at timestamp(6) with time zone,
    id bigint NOT NULL,
    manager_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    organization_id uuid NOT NULL,
    public_id uuid NOT NULL,
    created_by character varying(255),
    status character varying(255),
    updated_by character varying(255),
    CONSTRAINT relations_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'TERMINATED'::character varying])::text[])))
);

ALTER TABLE relations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME relations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE users (
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    organization_id uuid NOT NULL,
    public_id uuid NOT NULL,
    address_encrypted character varying(255),
    created_by character varying(255),
    email character varying(255),
    manager_type character varying(255),
    name character varying(255) NOT NULL,
    password character varying(255),
    phone_encrypted character varying(255),
    role character varying(255) NOT NULL,
    updated_by character varying(255),
    user_id character varying(255),
    CONSTRAINT users_manager_type_check CHECK (((manager_type)::text = 'PHYSICAL_THERAPIST'::text)),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['MANAGER'::character varying, 'CUSTOMER'::character varying])::text[])))
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY journal_templates
    ADD CONSTRAINT journal_templates_pkey PRIMARY KEY (journal_templates_id);

ALTER TABLE ONLY journal_templates
    ADD CONSTRAINT journal_templates_public_id_key UNIQUE (public_id);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (refresh_token_id);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT refresh_token_refresh_token_key UNIQUE (refresh_token);

ALTER TABLE ONLY relation_journals
    ADD CONSTRAINT relation_journals_pkey PRIMARY KEY (relation_journals_id);

ALTER TABLE ONLY relation_journals
    ADD CONSTRAINT relation_journals_public_id_key UNIQUE (public_id);

ALTER TABLE ONLY relations
    ADD CONSTRAINT relations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY relations
    ADD CONSTRAINT relations_public_id_key UNIQUE (public_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_public_id_key UNIQUE (public_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_user_id_key UNIQUE (user_id);

ALTER TABLE ONLY relations
    ADD CONSTRAINT fk6115g5143sp2fi39vruqobjst FOREIGN KEY (manager_id) REFERENCES users(id);

ALTER TABLE ONLY relations
    ADD CONSTRAINT fkdcc5d4psvxk9kmk9watny00hh FOREIGN KEY (customer_id) REFERENCES users(id);

ALTER TABLE ONLY relation_journals
    ADD CONSTRAINT fkkkqjkrc62x8ljli6opf8gw33x FOREIGN KEY (template_id) REFERENCES journal_templates(journal_templates_id);

ALTER TABLE ONLY relation_journals
    ADD CONSTRAINT fkp3nx399nvxkoatjnbp4fr80wl FOREIGN KEY (relation_id) REFERENCES relations(id);
