-- Identity Foundation: Platform Account / Password Credential / External Identity 신규 테이블.
-- 이 시점에는 FK/unique 제약을 걸지 않는다 (V4에서 데이터 정합성 확인 후 부여).

CREATE TABLE platform_accounts (
    id uuid NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'ACTIVE',
    primary_email character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT platform_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT platform_accounts_status_check CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- 1:1 - account_id 자체를 PK로 둬서 accountId unique 요건을 PK로 보장한다.
CREATE TABLE password_credentials (
    account_id uuid NOT NULL,
    login_id character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT password_credentials_pkey PRIMARY KEY (account_id)
);

CREATE TABLE external_identities (
    id bigint NOT NULL,
    account_id uuid NOT NULL,
    provider character varying(50) NOT NULL,
    provider_subject character varying(255) NOT NULL,
    email_snapshot character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT external_identities_pkey PRIMARY KEY (id)
);

ALTER TABLE external_identities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME external_identities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- CUSTOMER는 Platform Account가 아니므로 nullable. 전역 NOT NULL을 걸지 않는다.
ALTER TABLE users ADD COLUMN account_id uuid;
