-- CustomerEvent는 RelationJournal과 별개의 canonical Product persistence다.
-- TenantBaseEntity의 organization_id를 재사용하며, overdue는 저장하지 않는다.
CREATE TABLE customer_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL UNIQUE,
    organization_id uuid NOT NULL,
    customer_id bigint NOT NULL,
    status varchar(16) NOT NULL,
    scheduled_at timestamp(6) with time zone,
    occurred_at timestamp(6) with time zone,
    descriptor varchar(200),
    note text,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    created_by varchar(255),
    updated_by varchar(255),
    CONSTRAINT fk_customer_events_customer
        FOREIGN KEY (customer_id) REFERENCES users(id),
    CONSTRAINT customer_events_status_check
        CHECK (status IN ('PLANNED', 'OCCURRED', 'CANCELLED')),
    CONSTRAINT customer_events_time_check CHECK (
        (status = 'PLANNED' AND scheduled_at IS NOT NULL AND occurred_at IS NULL)
        OR (status = 'OCCURRED' AND occurred_at IS NOT NULL)
        OR (status = 'CANCELLED' AND scheduled_at IS NOT NULL AND occurred_at IS NULL)
    )
);

CREATE INDEX idx_customer_events_schedule
    ON customer_events (organization_id, scheduled_at)
    WHERE scheduled_at IS NOT NULL;

CREATE INDEX idx_customer_events_occurrence
    ON customer_events (organization_id, occurred_at)
    WHERE occurred_at IS NOT NULL;

CREATE INDEX idx_customer_events_customer_history
    ON customer_events (organization_id, customer_id, created_at DESC);
